### ISSUE TITLE
💥 GO.cmd fails when the variable ExtraBackup is not set

### ISSUE THREAD

**Issue by piaudonn** [TristankMS/TACARS#2]
The documentation doesn't mention that a backup folder have to be specified. Yet the GO script will fail if we leave it as-is.
I see that https://github.com/TristankMS/TACARS/commit/aaf6d479f4ace3a9099353be46bcfe16753a9088 is adding quotes to it thing `SET "ExtraBackup="` but that still fails with the error `The syntax of the command is incorrect.`. When echo is ON, we see it fails specificaly at this step:

![image](https://user-images.githubusercontent.com/22434561/151242556-cc0b559d-a6f4-4c22-a2d2-c8027754bcbb.png)

But I might have misread. @TristankMS what do you think?

In any case, if I do specify a path, then things work just fine and my Julio table gets populated.

**Comment by TristankMS** [comment]
Thanks Pierre... The intent of the script is that it creates ExtraBackup if specified, but should do nothing if not.

In the screenshot above, the line which is failing looks like the next one, unrelated to ExtraBackup (there might be two problems).

Hmm - tapping out each command in that list in CMD on my W10 box doesn't cause an error. The IF NOT "" line looks like the point of failure for you above, which looks unrelated to ExtraBackup... But ExtraBackup's broken for another reason - which _looks_ like I've just fundamentally misunderstood variable usage. Or that it changed. Probably the former! I have an alternative I'll implement which should make it more explicit and robust...

**Comment by TristankMS** [comment]
Yep, got it - aggressive nesting without similarly-aggressive testing. Fix I've got tests well so will check it in.

**Comment by piaudonn** [comment]
![BabyScreamYeahGIF](https://user-images.githubusercontent.com/22434561/151400941-f5f67de5-2b01-4169-938c-80770659682e.gif)

**Comment by TristankMS** [comment]
Reworked variable handling in Go_Template.cmd. Was considering splitting off the "run" part from the variable definition - so closer to editing a config file - but future aspiration is to go all-PowerShell, so minimal changes preferred.
